### ISSUE TITLE
Kubernetes Admission/Mutation Webhooks

### ISSUE THREAD

**Issue by IfSentient** [grafana/grafana-app-sdk#2]
In order to allow direct access to the underlying kubernetes API server, a user should be able to create admission/mutating webhooks to check for validity and enforce metadata constraints. 

We should provide a base mutating webhook that adds the CommonMetadata fields that are extensions on kubernetes metadata, and also add the labels we use internally in the SDK for determining underlying resource version (needed for automated version upgrade support, and for future possible SSA support).

**Comment by joeblubaugh** [comment]
How does the SDK participate in this? Is it a CLI command to install webhooks or is this meant to be done by an app at runtime?

**Comment by IfSentient** [comment]
The library aspects and local setup for validating and mutating admission have been introduced as of https://github.com/grafana/grafana-app-sdk/pull/29

**Comment by IfSentient** [comment]
Going to close this issue as the SDK components are complete, cloud registration will be a separate issue.
