### ISSUE TITLE
TypedStore.ForceDelete returning an error on not found

### ISSUE THREAD

**Issue by IfSentient** [grafana/grafana-app-sdk#209]
ForceDelete should return `nil` on a 404, but return any other error.

**Comment by IfSentient** [comment]
@radiohead I was unable to reproduce this issue with a local kubernetes setup--the only scenario where I can get `ForceDelete` to return an error is when the resource type itself doesn't exist, and I'm not sure if we want to return an error or not in that case.

**Comment by radiohead** [comment]
@IfSentient I wonder if this depends on the versions of the API server and the client-side k8s libraries. I'll have to test this locally and see if I can reproduce this issue with the exact same versions that I've originally detected this issue with.

**Comment by radiohead** [comment]
I've confirmed that this was a different issue.
