### ISSUE TITLE
[local] Enable k3d API Server Access via Grafana API Server in Local Dev Environment

### ISSUE THREAD

**Issue by IfSentient** [grafana/grafana-app-sdk#271]
In order to enable direct access to the API server, we need a way for the front-end grafana plugin to communicate directly with the API server using grafana auth. The likely most feasible way to do this (at least initially) is to have the k3d API extensions server (which serves CRD's) aggregated under the grafana API server, so that a front-end plugin can talk to the grafana API server to access their CRDs.

We need a solution that works with the manifests generated by `grafana-app-sdk project local generate` that will enable a front-end plugin to take the same actions on their kinds as the back-end plugin currently can, without needing that back-end proxy.

**Comment by toddtreece** [comment]
there are [docs](https://github.com/grafana/grafana/tree/main/pkg/services/apiserver/aggregator#testing-aggregation-locally) on how to configure aggregation, and [examples](https://github.com/grafana/grafana/tree/main/pkg/services/apiserver/aggregator/examples/manual-test) of what to apply. let me know if that will cover what you need
