### ISSUE TITLE
[CLI/codegen] Front-End Plugin Generated by CLI Doesn't Build

### ISSUE THREAD

**Issue by IfSentient** [grafana/grafana-app-sdk#76]
When generating a plugin front-end with 
```shell
grafana-app-sdk project component add frontend --plugin-id=foo
```
The generated plugin fails to build with the error:
```
$ grafana-toolkit plugin:build
No longer supported. Use grafana create-plugin https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [build/plugin-frontend] Error 1
```
Current workaround is to run
```
npx @grafana/create-plugin@latest migrate
```
in the `plugin` directory and reply `y` to all prompts, then create a `plugin/LICENSE` file (as this is not created by the migration).

However, the front-end code created by the CLI should work out-of-the-box and not require migration.

**Comment by joeblubaugh** [comment]
> $ grafana-toolkit plugin:build
> No longer supported. Use grafana create-plugin https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin

Is this going to happen to existing code if the app-sdk version is updated? Or does it apply only to new code?

**Comment by joeblubaugh** [comment]
It looks like it might:
> https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin#update-your-plugin-build-config
